export const TORONTO_HOODS = {
  libertyvillage: {
    slug: "liberty-village", name: "Liberty Village",
    hoodMult: 1.12, vsAvgPct: 12,
    description: "Liberty Village is a dense, young-professional neighbourhood in Toronto's west end, known for its converted loft buildings, tech offices, and walkable amenities.",
    context: "Newer purpose-built towers near the King Street streetcar tend toward the higher end.",
    nearbyHoods: ["Parkdale", "Queen West", "King West"],
  },
  leslieville: {
    slug: "leslieville", name: "Leslieville",
    hoodMult: 1.04, vsAvgPct: 4,
    description: "Leslieville is a popular east-end neighbourhood known for its independent cafes, restaurants, and mix of Victorian homes and newer rental buildings.",
    context: "Units closer to Queen Street East tend to command slightly higher rents.",
    nearbyHoods: ["Riverside", "East End", "Distillery District"],
  },
  annex: {
    slug: "annex", name: "Annex",
    hoodMult: 1.10, vsAvgPct: 10,
    description: "The Annex is a historic, tree-lined neighbourhood near the University of Toronto, popular with students, academics, and young professionals.",
    context: "Proximity to U of T and Bloor Street drives strong year-round rental demand.",
    nearbyHoods: ["Yorkville", "Midtown", "Davisville"],
  },
  queenswest: {
    slug: "queen-west", name: "Queen West",
    hoodMult: 1.15, vsAvgPct: 15,
    description: "Queen West is one of Toronto's most vibrant neighbourhoods, known for its arts scene, boutiques, and nightlife. It commands a significant premium over the city average.",
    context: "Units on quieter side streets north of Queen offer slightly better value.",
    nearbyHoods: ["Parkdale", "Liberty Village", "Kensington Market"],
  },
  yorkville: {
    slug: "yorkville", name: "Yorkville",
    hoodMult: 1.30, vsAvgPct: 30,
    description: "Yorkville is Toronto's most prestigious neighbourhood, home to luxury condos, high-end retail, and some of the city's highest rents.",
    context: "This is consistently one of the most expensive rental markets in Canada.",
    nearbyHoods: ["Annex", "Midtown", "Forest Hill"],
  },
  northyork: {
    slug: "north-york", name: "North York",
    hoodMult: 0.90, vsAvgPct: -10,
    description: "North York offers a mix of suburban and urban living with good transit access via the Yonge-University subway line. Rents are meaningfully below the downtown core.",
    context: "Proximity to subway stations drives rent premiums within North York itself.",
    nearbyHoods: ["Willowdale", "Lawrence Park", "Midtown"],
  },
  scarborough: {
    slug: "scarborough", name: "Scarborough",
    hoodMult: 0.82, vsAvgPct: -18,
    description: "Scarborough is Toronto's most affordable major district, offering significantly lower rents than the downtown core while still connected by the Bloor-Danforth subway.",
    context: "Rents are well below the city average, making Scarborough one of Toronto's best value options.",
    nearbyHoods: ["East End", "North York", "East York"],
  },
  distillery: {
    slug: "distillery", name: "Distillery District",
    hoodMult: 1.20, vsAvgPct: 20,
    description: "The Distillery District is a historic neighbourhood of converted Victorian industrial buildings now housing condos, restaurants, and galleries.",
    context: "Premium finishes and historic character push rents toward the higher end of the city.",
    nearbyHoods: ["St. Lawrence", "Leslieville", "Riverside"],
  },
  parkdale: {
    slug: "parkdale", name: "Parkdale",
    hoodMult: 0.93, vsAvgPct: -7,
    description: "Parkdale is a diverse, evolving neighbourhood in Toronto's west end with a strong arts community and a mix of older walk-up apartments and newer builds.",
    context: "Rents are slightly below the city average, offering relative value close to downtown.",
    nearbyHoods: ["Queen West", "Liberty Village", "Roncesvalles"],
  },
  stlawrence: {
    slug: "st-lawrence", name: "St. Lawrence",
    hoodMult: 1.09, vsAvgPct: 9,
    description: "St. Lawrence is a well-established downtown neighbourhood known for the St. Lawrence Market, strong walkability, and a mix of condo and rental buildings close to the financial core.",
    context: "Central location and market proximity make this a consistently high-demand area.",
    nearbyHoods: ["Distillery District", "Leslieville", "Financial District"],
  },
  etobicoke: {
    slug: "etobicoke", name: "Etobicoke",
    hoodMult: 0.86, vsAvgPct: -14,
    description: "Etobicoke is a large western district of Toronto offering a mix of suburban and urban living. It has excellent highway access and a diverse range of rental options from high-rise towers to townhomes.",
    context: "Rents are well below the city average, making Etobicoke one of Toronto's better-value options for families.",
    nearbyHoods: ["Roncesvalles", "Parkdale", "Mississauga"],
  },
  kingwest: {
    slug: "king-west", name: "King West",
    hoodMult: 1.18, vsAvgPct: 18,
    description: "King West is one of Toronto's most sought-after neighbourhoods for young professionals, featuring a dense corridor of restaurants, bars, and mixed-use condo towers along King Street West.",
    context: "Newer condo rentals dominate the market. High demand from tech and finance workers keeps vacancy low.",
    nearbyHoods: ["Liberty Village", "Queen West", "Entertainment District"],
  },
  kensingtonmarket: {
    slug: "kensington-market", name: "Kensington Market",
    hoodMult: 1.02, vsAvgPct: 2,
    description: "Kensington Market is one of Toronto's most distinctive and eclectic neighbourhoods, known for its independent vendors, cultural diversity, and strong sense of community.",
    context: "Rents are close to the city average. Older housing stock and walk-up apartments are common.",
    nearbyHoods: ["Annex", "Queen West", "Chinatown"],
  },
  roncesvalles: {
    slug: "roncesvalles", name: "Roncesvalles",
    hoodMult: 1.06, vsAvgPct: 6,
    description: "Roncesvalles is a beloved west-end neighbourhood with a Polish heritage, tree-lined streets, independent shops, and a strong community feel. It is popular with families and young professionals alike.",
    context: "Rents are modestly above the city average. Demand is driven by the neighbourhood's character and proximity to the lake.",
    nearbyHoods: ["Parkdale", "Etobicoke", "High Park"],
  },
  midtown: {
    slug: "midtown", name: "Midtown",
    hoodMult: 1.12, vsAvgPct: 12,
    description: "Midtown Toronto encompasses established neighbourhoods like Davisville and Mount Pleasant, offering a balance of urban amenities, transit access, and quieter residential streets.",
    context: "Strong subway access and proximity to premier schools keep demand consistently above the city average.",
    nearbyHoods: ["Yorkville", "North York", "Annex"],
  },
  cabbagetown: {
    slug: "cabbagetown", name: "Cabbagetown",
    hoodMult: 1.08, vsAvgPct: 8,
    description: "Cabbagetown is one of Toronto's oldest and most charming neighbourhoods, known for its preserved Victorian row houses and quiet, walkable streets east of downtown.",
    context: "Heritage character and central location support rents moderately above the city average.",
    nearbyHoods: ["St. Lawrence", "Distillery District", "Regent Park"],
  },
  harbourfront: {
    slug: "harbourfront", name: "Harbourfront",
    hoodMult: 1.22, vsAvgPct: 22,
    description: "Harbourfront is Toronto's waterfront neighbourhood, offering stunning lake views, a mix of luxury condos, and easy access to the PATH and financial district.",
    context: "Lake views and premium finishes push rents well above the city average. Newer condo towers dominate.",
    nearbyHoods: ["King West", "St. Lawrence", "Financial District"],
  },
  eastyork: {
    slug: "east-york", name: "East York",
    hoodMult: 0.91, vsAvgPct: -9,
    description: "East York is a quieter inner-suburb east of the downtown core, known for its bungalow streets, good parks, and Danforth Avenue amenities. It offers solid value relative to the city average.",
    context: "Rents are below the city average. Good Bloor-Danforth subway access supports consistent demand.",
    nearbyHoods: ["Scarborough", "Leslieville", "North York"],
  },
  foresthill: {
    slug: "forest-hill", name: "Forest Hill",
    hoodMult: 1.28, vsAvgPct: 28,
    description: "Forest Hill is one of Toronto's most affluent neighbourhoods, with prestigious private schools, large homes, and a quiet, established character that commands significant rent premiums.",
    context: "Rental supply is limited and demand from families and executives keeps prices consistently elevated.",
    nearbyHoods: ["Yorkville", "Midtown", "Annex"],
  },
};

export const TORONTO_CITY = {
  key: "toronto", name: "Toronto", province: "Ontario",
  accent: "#1a5c34", accentLight: "#f0f7f2", accentBorder: "#a8d5b5",
  calcUrl: "https://torontofairrent.ca",
  bases: { bachelor:1800, "1br":2400, "2br":3100, "3br":3900, "3plus":4800 },
  inflation: 0.040, rentControlled: true,
};
